# Generated by Django 4.0.3 on 2022-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_genders_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genders',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6),
        ),
        migrations.DeleteModel(
            name='authorprofile',
        ),
        migrations.DeleteModel(
            name='genders',
        ),
    ]
