# Generated by Django 4.0.3 on 2022-03-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
    ]
