# Generated by Django 4.0.3 on 2022-03-03 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_profile_img_profileimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
