# Generated by Django 4.0.3 on 2022-03-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_profileimage_vanue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='vanue_image',
        ),
    ]
