# Generated by Django 4.0.3 on 2022-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_profileimage_vanue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
