# Generated by Django 4.0.3 on 2022-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/event_pic'),
        ),
    ]
