# Generated by Django 4.0.3 on 2022-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='Admin', max_length=10),
        ),
    ]
