# Generated by Django 4.0.3 on 2022-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_user_genders_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='usrname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
