# Generated by Django 3.1.7 on 2022-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20220330_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
