# Generated by Django 3.1.7 on 2022-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20220428_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='tp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50, verbose_name='eid')),
                ('ename', models.CharField(max_length=50, verbose_name='ename')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
