# Generated by Django 3.1.7 on 2022-04-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_auto_20220428_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tp',
        ),
    ]
