# Generated by Django 3.1.7 on 2022-04-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='eid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ORDERID',
            field=models.IntegerField(default=0, verbose_name='ORDERID'),
        ),
    ]
