# Generated by Django 3.1.7 on 2022-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20220428_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ORDERID',
        ),
        migrations.AddField(
            model_name='transaction',
            name='eid',
            field=models.IntegerField(default=0, verbose_name='eid'),
        ),
    ]
