# Generated by Django 3.1.7 on 2022-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20220428_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pdate',
        ),
        migrations.AddField(
            model_name='user',
            name='otpverify',
            field=models.BooleanField(default=False),
        ),
    ]
