# Generated by Django 3.1.7 on 2022-05-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_auto_20220502_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=120, verbose_name='Event_Name')),
                ('eventid', models.IntegerField(default=0, verbose_name='eid')),
                ('eventimg', models.CharField(max_length=200, verbose_name='EventImg')),
                ('eventprice', models.IntegerField(verbose_name='EventPrice')),
                ('username', models.CharField(max_length=120, verbose_name='UserName')),
                ('paymentstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
