# Generated by Django 3.1.7 on 2022-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20220509_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='eventid',
            field=models.CharField(max_length=120, verbose_name='Event_Id'),
        ),
    ]
