# Generated by Django 3.1.7 on 2022-05-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_auto_20220509_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='eventid',
        ),
    ]
