# Generated by Django 3.1.7 on 2022-05-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_cart_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='eventprice',
            field=models.IntegerField(null=True, verbose_name='EventPrice'),
        ),
    ]
